openapi: '3.0.2'
info:
  title: Techo Blog API
  version: '1.0'
servers:
  - url: https://api.server.test/v1
tags:
  - name: auth
    description: Endpoints for managing users authorising
  - name: user
    description: Endpoints for managing users 
  - name: article
    description: Endpoints for managing articles
paths:
  /auth/register:
    post:
      summary: Register a new user
      tags:
        - auth
      description: Create a new user. All the fields are required
      operationId: registerUser
      x-eov-operation-handler: authController
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                  format: int64
                name: 
                  type: string
                lastname:
                  type: string
                email:  
                  type: string
                password: 
                  type: string
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                    default: 201
                  message:
                    type: string
                    default: Created
                  data: 
                    type: object
                    properties:
                      id:
                        type: integer
                        format: int64
                      name:
                        type: string
                      lastname: 
                        type: string
                      email:  
                        type: string
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                    default: 400
                  message:
                    type: string
                    default: Bad Request
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                    default: 403
                  message:
                    type: string
                    default: Forbidden         
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema: 
                type: object
                properties:
                  statusCode:
                    type: integer
                    default: 500
                  message:
                    type: string
                    default: Internal Server Error

  /auth/login:
    post:
      summary: Login a user
      tags:
        - auth
      description: Login a user. If the user is logged correctly, we return a JWT. 
      operationId: loginUser
      x-eov-operation-handler: authController
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string      
                password:
                  type: string
      responses:           
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                    default: 200
                  message:
                    type: string
                    default: Ok
                  jwt: 
                    type: string
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                    default: 400
                  message:
                    type: string
                    default: Bad Request      
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                    default: 500
                  message:
                    type: string
                    default: Internal Server Error

  /user:
    get:
      summary: Get a list of users
      tags:
        - user
      description: Get a list of users
      operationId: getUsers
      x-eov-operation-handler: userController
      parameters:
        - in: query
          name: limit
          schema:
            type: integer
          required: true
        - in: query
          name: page
          schema:
            type: integer
          required: true
        - in: query
          name: find
          schema: 
            type: integer
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                    default: 200
                  message:
                    type: string
                    default: Ok
                  count:
                    type: integer
                  data: 
                    type: array
                    items:
                      type: object
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                    default: 400
                  message: 
                    type: string
                    default: Bad Request
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                    default: 401
                  message:
                    type: string
                    default: Unauthorized
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                    default: 500
                  message:
                    type: string
                    default: Internal Server Error
  
  /user/{id}:
    get:
      summary: Get a user with specific id
      tags:
        - user
      description: Get a user with specific id
      operationId: getUser
      x-eov-operation-handler: userController
      parameters:
        - in: path
          name: userId
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                    default: 200
                  message:
                    type: string
                    default: Ok
                  data: 
                    type: object
                    properties:
                      name: 
                        type: string
                      lastname:
                        type: string
                      email:
                        type: string
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                    default: 400
                  message:
                    type: string
                    default: Bad Request
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                    default: 401
                  message:
                    type: string
                    default: Unauthorized
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                    default: 500
                  message:
                    type: string
                    default: Internal Server Error
    put:
      summary: Update an user
      tags:
        - user
      description: Update an user
      operationId: putUser
      x-eov-operation-handler: userController
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                lastname:
                  type: string
                email:
                  type: string
                password:
                  type: string
      parameters:
        - in: path
          name: userId
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                    default: 200
                  message:
                    type: string
                    default: Ok
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                        format: int64
                      name:
                        type: string
                      lastname:
                        type: string
                      password:
                        type: string
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                    default: 400
                  message:
                    type: string
                    default: Bad Request
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                    default: 401
                  message:
                    type: string
                    default: Unauthorized
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                    default: 500
                  message:
                    type: string
                    default: Internal Server Error
    delete:
      summary: Update an user
      tags:
        - user
      description: Delete an user
      operationId: deleteUser
      x-eov-operation-handler: userController
      parameters:
        - in: path
          name: userId
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                    default: 200
                  message:
                    type: string
                    default: Ok
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                        format: int64
                      name:
                        type: string
                      lastname:
                        type: string
                      password:
                        type: string
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                    default: 400
                  message:
                    type: string
                    default: Bad Request
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                    default: 401
                  message:
                    type: string
                    default: Unauthorized
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                    default: 500
                  message:
                    type: string
                    default: Internal Server Error